spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:leaderboard
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
